### ISSUE TITLE
MMS Cannot find module 'strtok3/lib/type'

### ISSUE THREAD

**Issue by edvallie** [mediamonkeyserver/mms#29]
Looks like the more modern versions of strtok3 have changed type.js -> types.js and it's causing an error.
```
mediamonkey@dax:/var/www/mediamonkey/mms$ npm start

> mediamonkeyserver@0.3.1 start /var/www/mediamonkey/mms
> node server.js

Database loaded in 7 ms
(node:17712) UnhandledPromiseRejectionWarning: Error: Cannot find module 'strtok3/lib/type'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/mediamonkey/mms/node_modules/music-metadata/lib/aiff/AiffParser.js:5:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/mediamonkey/mms/node_modules/music-metadata/lib/ParserFactory.js:8:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
(node:17712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17712) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Steps to reproduce on ubuntu 16.04.6

git clone https://github.com/mediamonkeyserver/mms.git
cd mms
npm install
npm start

Resolved by either symlinking back to the old name or upgrading the music-metadata package in package.json to "^6.3.0" and doing an npm install

**Comment by jirihajek** [comment]
Merged, closing. Thanks for the fix!
