### ISSUE TITLE
installing mms on synology nas: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mluerig** [mediamonkeyserver/mms#51]
hi, I'm trying to install mms on my synology nas via ssh. I install make and gcc via ipkg. then I cloned the repo, and ran  `npm intall` inside the folder, but then I got this error:

    mluerig@ml-nas:~/mms$ npm install
    
    > better-sqlite3@7.1.1 install /volume1/homes/mluerig/mms/node_modules/better-sqlite3
    > prebuild-install || npm run build-release
    
    prebuild-install WARN install No prebuilt binaries found (target=12.20.1 runtime=node arch=x64 libc= platform=linux)
    
    > better-sqlite3@7.1.1 build-release /volume1/homes/mluerig/mms/node_modules/better-sqlite3
    > node-gyp rebuild --release
    
    make: Entering directory '/volume1/homes/mluerig/mms/node_modules/better-sqlite3/build'
      TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
      ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
      TOUCH Release/obj.target/deps/locate_sqlite3.stamp
      CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
      AR(target) Release/obj.target/deps/sqlite3.a
    ar: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
    deps/sqlite3.target.mk:203: recipe for target 'Release/obj.target/deps/sqlite3.a' failed
    make: *** [Release/obj.target/deps/sqlite3.a] Error 127
    rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
    make: Leaving directory '/volume1/homes/mluerig/mms/node_modules/better-sqlite3/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
    gyp ERR! System Linux 4.4.59+
    gyp ERR! command "/volume1/@appstore/Node.js_v12/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /volume1/homes/mluerig/mms/node_modules/better-sqlite3
    gyp ERR! node -v v12.20.1
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! better-sqlite3@7.1.1 build-release: `node-gyp rebuild --release`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the better-sqlite3@7.1.1 build-release script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /var/services/homes/mluerig/.npm/_logs/2021-06-26T11_06_27_132Z-debug.log
    npm WARN @semantic-release/git@4.0.3 requires a peer of semantic-release@>=15.0.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! better-sqlite3@7.1.1 install: `prebuild-install || npm run build-release`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the better-sqlite3@7.1.1 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /var/services/homes/mluerig/.npm/_logs/2021-06-26T11_06_28_098Z-debug.log

**Comment by jirihajek** [comment]
Have you tried to pre-built binaries from https://www.mediamonkey.com/forum/viewtopic.php?f=31&t=90809?

Building on Synology is tricky, we actually use cross-compilation there. If you are interested, you can check out scripts/build-armv7-synology.js and related code to compile the binaries yourself.

**Comment by mluerig** [comment]
thanks! so, I would compile it on a desktop machine and then install it my nas?

**Comment by jirihajek** [comment]
Yes, unless you want to just download and use the compiled builds, you can run `npm run build-armv7-synology` or `npm run build-armv8-synology` to compile sqlite. The scripts are there to prepare the whole packages (custom node build for pkg script), but you can only extract sqlite if you want.

**Comment by mluerig** [comment]
I want to give the prebuilt binaries a try first, but I am not sure how I would "Extract the files to a directory and run mms." run, exactly how? and can I run it from DSM?

**Comment by jirihajek** [comment]
We don't have a DSM package yet, so a terminal access is needed (probably, not sure whether there's another solution). The archive can be then extracted using tar and executed as './mms'.

**Comment by mluerig** [comment]
I have tried what you suggested, i.e., download the binaries, extracted them to home, and running "./mms" - but this doesn't do anything. there is probably some misunderstanding from my side. Here is the console output, mms is a folder containing the tar.gz contents

    ´drwxrwxrwx  1 mluerig users                 66 Jul  7 17:02 mms
    -rw-r--r--  1 mluerig users           48608800 Jan 13  2021 MMS-armv7-0.3.2.tar.gz
    
    mluerig@ml-nas:~$ ./mms
    -sh: ./mms: Is a directory
    mluerig@ml-nas:~$ cd mms
    mluerig@ml-nas:~/mms$ ./mms
    -sh: ./mms: Permission denied
    mluerig@ml-nas:~/mms$ sudo ./mms
    Password:
    sudo: ./mms: command not found
    mluerig@ml-nas:~/mms$ sudo ./mms
    sudo: ./mms: command not found
    mluerig@ml-nas:~/mms$

**Comment by jirihajek** [comment]
Sorry, for the late answer. I'm not sure why the prebuilt binary can't be started. However, I'd recommend to return to the original attempt, i.e. to run `npm install` (after updating the repo). There has been a lot of improvements in better-sqlite3 and so I hope it might work right out of the box now. If not, I could send you its armv7 build then. Thanks!
