### ISSUE TITLE
command failed: sh -c npm run buildUI

### ISSUE THREAD

**Issue by rabelux** [mediamonkeyserver/mms#54]
Hi all,
I'm trying to set up mms on my headless linux server (arm64) and `npm install` fails with said error.
Environment:
- Armbian 21.08.3 Buster with Linux 5.10.63-rockchip64
- `node -v`: v17.0.1
- `npm -v`: 8.1.0

logfile:
[2021-11-03T13_09_55_797Z-debug.log](https://github.com/mediamonkeyserver/mms/files/7467830/2021-11-03T13_09_55_797Z-debug.log)

I'll test https://www.mediamonkey.com/beta/mms/MMS-arm64-0.4.1.tar.gz next and report back.

**Comment by jirihajek** [comment]
Hi, looks like a problem with execution of the 'postinstall' command, which is `npm run buildUI`. Could you try to execute this command manually?

**Comment by rabelux** [comment]
The downloaded exetuable has this output:
```
MMS v0.4.1 running at http://10.8.0.1:10222 (or http://localhost:10222)
Connect using a web browser or using MediaMonkey 5.
==================================================
Scanning of /root/Videos has failed: Error: Can not scan directory
NAT setup doesn't work: Error: Request failed: 500
```

Why does it run at 10.8.0.1? That's my VPN subnet, I'd rather have it at 10.1.1.5.
Relevant output of `ifconfig`:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.1.5  netmask 255.255.255.0  broadcast 10.1.1.255
        ether e6:55:41:37:b9:57  txqueuelen 1000  (Ethernet)
        RX packets 153382935  bytes 141444619234 (131.7 GiB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 170866358  bytes 221190912533 (206.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 35
tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.0  destination 10.8.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 4198  bytes 681622 (665.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4003  bytes 2738856 (2.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by rabelux** [comment]
> 
> 
> Hi, looks like a problem with execution of the 'postinstall' command, which is `npm run buildUI`. Could you try to execute this command manually?

That was quick! I was running out of disk space so unfortunately I deleted everything. Sorry. Need to find a bigger sd-card as I don't want to be running on a 95 % filled partition.

**Comment by jirihajek** [comment]
> Why does it run at 10.8.0.1? That's my VPN subnet, I'd rather have it at 10.1.1.5.

Thanks, there'll be somewhat better IP detection code in the next version, which should fix your case. Although, to be honest, I'm not sure how to make this part fully bulletproof.

> I was running out of disk space so unfortunately I deleted everything.

Np, please let me know later.

**Comment by rabelux** [comment]
> Node-gyp build tools (https://github.com/nodejs/node-gyp)
> On an elevated command prompt run: npm install -global windows-build-tools
> Then, run npm config set msvs_version 2017

Is said part from the readme relevant for Linux?

I did run `npm run buildUI` and this is the output:
```
> mediamonkeyserver@0.4.1 buildUI
> node scripts/buildUI.js

Using npm for building UI.
Installing necessary build modules. This may take a few minutes... Do not terminate the process.

up to date, audited 1720 packages in 21s

64 packages are looking for funding
  run `npm fund` for details

115 vulnerabilities (43 moderate, 69 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Building web UI. This may take a few minutes... Do not terminate the process.

> mms-ui@0.1.0 build
> react-scripts build

Setting NODE_PATH to resolve modules absolutely has been deprecated in favor of setting baseUrl in jsconfig.json (or tsconfig.json if you are using TypeScript) and will be removed in a future major release of create-react-app.

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/opt/MMS_nightly/webui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:503:5
    at /opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:358:12
    at /opt/MMS_nightly/webui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/opt/MMS_nightly/webui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/opt/MMS_nightly/webui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/opt/MMS_nightly/webui/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/opt/MMS_nightly/webui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:417:16)
    at /opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:452:10
    at /opt/MMS_nightly/webui/node_modules/webpack/lib/NormalModule.js:323:13
    at /opt/MMS_nightly/webui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /opt/MMS_nightly/webui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/opt/MMS_nightly/webui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /opt/MMS_nightly/webui/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'cordova/www/index.html'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/opt/MMS_nightly/scripts/buildUI.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'cordova/www/index.html'
}

Node.js v17.0.1
```

Off-topic question:
Could you link the mm-forum-thread with precompiled binaries either in *About* or in the readme?

**Comment by jirihajek** [comment]
The error seems to be because of problems between Node 17 and Webpack 4 (https://github.com/webpack/webpack/issues/14532). I'll try to upgrade to Webpack 5 soon, until then there's a suggested workaround `export NODE_OPTIONS=--openssl-legacy-provider` (see the linked webpack issue).

**Comment by jirihajek** [comment]
> Could you link the mm-forum-thread with precompiled binaries either in About or in the readme?

Good idea, done. Thanks!

**Comment by rabelux** [comment]
Entering `export NODE_OPTIONS=--openssl-legacy-provider` did indeed solve the issue and it's working now. Thanks!

Regarding IP detection: It still shows my VPN address as 10.8.x probably overrides 10.1.x in priority3. I suggest to continue this discussion [here](https://github.com/mediamonkeyserver/mms/commit/2a6b7943506db39fc152390a16addef83fd7e178)

Remaining unanswered question:
Is it necessary to install Node-gyp build tools on linux?

**Comment by rabelux** [comment]
> Is it necessary to install Node-gyp build tools on linux?

I just deleted that package and I am still able to build mms. So from my perspective it's not needed.

**Comment by jirihajek** [comment]
Reopening to track the need to upgrade Webpack.

As for node-gyp - the requirements for various platforms need to be updated. I just made some changes to README which reflect my current knowledge, but I'm not sure it properly covers everything.
